---
    - name: Installation of aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Installing required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Addding Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Addding Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Updating apt and installing docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Installing Docker Module for Python
      pip:
        name: docker
      notify:
      - Restart docker  

...
